version: "3"

services:
  mongo:
    image: mongo
    container_name: mongodb
    restart: always
  api:
    container_name: api
    restart: unless-stopped
    build: .
    ports:
      - "5000:5000/tcp"
      - "2000-2020:2000-2020/udp"
      - "2000-2020:2000-2020/tcp"
    environment:
      - PORT=5000
      - MEDIASOUP_MIN_PORT=2000
      - MEDIASOUP_MAX_PORT=2020
      - LISTEN_IP=0.0.0.0
      - WEB_URL=http://localhost:3000
      - MONGO_URL=mongodb://mongo:27017/uhhhh
      - ANNOUNCED_IP=127.0.0.1
      - SENTRY_DSN=
    depends_on:
      - mongo
  #    env_file:
  #      - .env
  web:
    container_name: web
    restart: unless-stopped
    ports:
      - 3000:3000
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    depends_on:
      - api

volumes:
  mongo-data:
# -- .env --
# MONGO_URL=
# NODE_ENV=
# ANNOUNCED_IP=
# SENTRY_DSN=
