version: "3"

services:
  api:
    container_name: api
    restart: unless-stopped
    image: kamalyb/uhhhh-api
    ports:
      - "5000:5000/tcp"
      - "2000-2020:2000-2020/udp"
      - "2000-2020:2000-2020/tcp"
    environment:
      - PORT=5000
      - MEDIASOUP_MIN_PORT=2000
      - MEDIASOUP_MAX_PORT=2020
      - LISTEN_IP=0.0.0.0
      - WEB_URL=http://localhost:3000
    env_file:
      - .env

# -- .env --
# MONGO_URL=
# NODE_ENV=
# ANNOUNCED_IP=
# SENTRY_DSN=