version: "3.9"

services:
  mongo:
    image: mongo
    container_name: uhhhh-mongo
    restart: always
  api:
    container_name: uhhhh-api
    restart: unless-stopped
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    ports:
      - "2300:2300/tcp"
      - "2000-2020:2000-2020/udp"
      - "2000-2020:2000-2020/tcp"
    environment:
      - PORT=2300
      - MEDIASOUP_MIN_PORT=2000
      - MEDIASOUP_MAX_PORT=2020
      - LISTEN_IP=0.0.0.0
      - WEB_URL=http://localhost:3000
      - MONGO_URL=mongodb://mongo:27017/uhhhh
      - ANNOUNCED_IP=127.0.0.1
      - SENTRY_DSN=
    depends_on:
      - mongo
  web:
    container_name: uhhhh-web
    restart: unless-stopped
    ports:
      - "3000:3000"
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    depends_on:
      - api
