services:
  api:
    image: kamalyb/uhhhh-api
    restart: unless-stopped
    ports:
      - "2300:2300/tcp"
      - "2000-2020:2000-2020/udp"
      - "2000-2020:2000-2020/tcp"
    environment:
      - NODE_ENV=production
      - PORT=2300
      - MEDIASOUP_MIN_PORT=2000
      - MEDIASOUP_MAX_PORT=2020
      - LISTEN_IP=0.0.0.0
      - WEB_URL=http://localhost:3000
      - ANNOUNCED_IP=127.0.0.1